### ISSUE TITLE
Python 3.7 support?

### ISSUE THREAD

**Issue by rjmill** [marksparkza/jschon#1]
I'd love to use this in a python 3.7 project. (Unfortunately, I can't upgrade the Python version for that project.)

I'm happy to open a PR for it if you're okay with supporting 3.7.

**Comment by marksparkza** [comment]
As discussed on slack, I'd prefer not to support 3.7 at this stage, as I've used the 'walrus' operator (introduced in python 3.8) quite extensively.

Hopefully a 3.7-ized fork will work for your project, and I'd be happy for you to contribute any fixes back upstream.
