### ISSUE TITLE
File not found for GeoJSON schema

### ISSUE THREAD

**Issue by IdrissaD** [marksparkza/jschon#10]
Hello!

I'm trying to validate a file against a schema I made myself, and I'm referencing other schemas in my `$defs`:
 ```
"$defs": {
    "GeoJSON_LineString" : {
      "$id": "linestring",
      "$ref": "https://geojson.org/schema/LineString.json"
    },
    "GeoJSON_Point" : {
      "$id": "point",
      "$ref": "https://geojson.org/schema/Point.json"
    },
    "GeoJSON_MultiLineString" : {
      "$id": "multilinestring",
      "$ref": "https://geojson.org/schema/MultiLineString.json"
    }
```
I get an error:  `jschon.exceptions.CatalogueError: File not found for 'https://geojson.org/schema/LineString.json'`
Do you have an idea to overcome this?

**Comment by marksparkza** [comment]
Hi @IdrissaD!

You can use the Catalogue.add_directory method to set up a URI-to-directory mapping, at the place where you initialize the catalogue. Something like the following should work:

```
from jschon import Catalogue, URI

catalogue = Catalogue.create_default_catalogue('2020-12')
catalogue.add_directory(URI('https://geojson.org/schema/'), '/path/to/schema/')
```

**Comment by IdrissaD** [comment]
Thanks for the answer! It seems like tho good method to use, but I confess that I struggle to understand it, even after reading the docs.
For now I have:
```
import json

from jschon import Catalogue, JSON, JSONSchema, URI
from pprint import pp

e = open('exemple-valide.json',)
s = open('schema.json',)

catalogue = Catalogue.create_default_catalogue('2020-12')
catalogue.add_directory(URI('https://geojson.org/schema/'), '/')

instance_to_validate = JSON(json.load(e))
schema = JSONSchema(json.load(s))


pp(schema.evaluate(instance_to_validate).valid)
```
I'm creating a JSON Schema and my goal is to provide a validator with the schema, so that people can easily validate their files against it. I'm referencing to GeoJSON schemas URI because it's necessary that the schema follows the evolution of GeoJSON specs.
I tried the `add_directory` method but I get the same error when the script executes `JSONSchema(json.load(s))`.
I don't quite understand what is the `base_dir` I have to provide: is it the local dir where my schema is stored? So it should be `/`? 

Here is the full Traceback if needed:
```
Traceback (most recent call last):
  File "/home/idrissa/dev/schema_randonnee/validator.py", line 19, in <module>
    schema = JSONSchema(json.load(s))
  File "/home/idrissa/dev/schema_randonnee/venv/lib/python3.9/site-packages/jschon/jsonschema.py", line 133, in __init__
    self._resolve_references()
  File "/home/idrissa/dev/schema_randonnee/venv/lib/python3.9/site-packages/jschon/jsonschema.py", line 164, in _resolve_references
    item._resolve_references()
  File "/home/idrissa/dev/schema_randonnee/venv/lib/python3.9/site-packages/jschon/jsonschema.py", line 154, in _resolve_references
    kw.resolve()
  File "/home/idrissa/dev/schema_randonnee/venv/lib/python3.9/site-packages/jschon/vocabulary/core.py", line 103, in resolve
    self.refschema = self.parentschema.catalogue.get_schema(uri, metaschema_uri=self.parentschema.metaschema_uri)
  File "/home/idrissa/dev/schema_randonnee/venv/lib/python3.9/site-packages/jschon/catalogue/__init__.py", line 264, in get_schema
    doc = self.load_json(base_uri)
  File "/home/idrissa/dev/schema_randonnee/venv/lib/python3.9/site-packages/jschon/catalogue/__init__.py", line 147, in load_json
    raise CatalogueError(f"File not found for '{uri}'")
jschon.exceptions.CatalogueError: File not found for 'https://geojson.org/schema/LineString.json'
```

**Comment by marksparkza** [comment]
`base_dir` is the local directory path that you wish to correspond with `base_uri`. Suppose that your `LineString.json` and other schema files are stored in the directory `/home/idrissa/schema/`, then you would say:
```
catalogue.add_directory(URI('https://geojson.org/schema/'), '/home/idrissa/schema/')
```
This would also work:
```
catalogue.add_directory(URI('https://geojson.org/'), '/home/idrissa/')
```
because what happens is that in resolving the `$ref` to `https://geojson.org/schema/LineString.json`, the catalogue matches the `https://geojson.org/` part of the URI against your local `/home/idrissa/` directory, and then simply appends the remaining part of the URI - `schema/LineString.json` - to the local path, and therefore loads the file `/home/idrissa/schema/LineString.json`.

Hope that makes sense!

**Comment by marksparkza** [comment]
Btw, you can load your JSON and schema files directly using the JSON and JSONSchema classes, for example:
```
instance_to_validate = JSON.loadf('exemple-valide.json')
schema = JSONSchema.loadf('schema.json')
```

**Comment by IdrissaD** [comment]
Ok I think it makes sense, so if I understand well, I can't validate a schema with a `$ref` to a file that isn't stored locally, right? I don't have LineString.json in my directories, I'm linking directly to the files on the geojson.org website.
Thanks for the `loadf` tip!

**Comment by marksparkza** [comment]
Ah, yes that's correct, unfortunately jschon does not yet support loading of remote schemas. It's in the development pipeline!

**Comment by IdrissaD** [comment]
Aaah ok! It's too bad as jschon is the only Python validator supporting 2020-12, maybe I'll have use another language. Thank you for the help and the validator =)
