### ISSUE TITLE
Ability to integrate large enums through custom code

### ISSUE THREAD

**Issue by ShahimEssaid** [marksparkza/jschon#14]
I'm evaluating the feasibility of using JSON Schema 2020-12 and jschon for data validation for a project that will include enumerations that contain thousands of codes from medical terminologies. I have not yet looked through jschon's API or source code to understand how I might be able to integrate custom code to apply any validation for these specific enumerations so they don't have to be listed in the schemas themselves. Also, any error output can't list the possible values. Instead, it would be enough to mention the enum $id and users will understand what that means.

I'm also still learning JSON Schema 2020-12, and so far I've only used jschon through jschon.dev. I'm assuming that if I always $ref such enum schemas with their $id, I might be able to extend jschon to recognize these $refs and apply custom logic for those specific $refs/$ids. The values for these enums will be obtained and cached from independent and remote terminology services.

Does jschon have an extension point to help with such integrations? If not, what are my best options? Any other JSON Schema implementation of 2020-12 that I should be considering that might better accommodate such a use case?

Thank you in advance for any suggestions.

**Comment by marksparkza** [comment]
I can't think of an obvious way to conditionally override the behaviour of an existing keyword like $ref using jschon.

However, in the JSON Schema way of thinking, a $ref should only ever behave like a $ref. To introduce a new keyword behaviour, you'd create a vocabulary (itself a JSON schema) describing the syntax for a new keyword - in this case we might call it "enumRef" - and then you'd write the code to implement the behaviour for that new keyword using some JSON Schema implementation.

jschon follows this idea of extensibility. You'd define an `EnumRefKeyword` class that can retrieve an enum given its URI and decide whether a given string instance is valid. This class can provide custom error messages and can add annotations into the output for successful validations. You'd write a few lines of boilerplate code to compile your metaschema and vocabulary definition files. And then it's standard usage for validating your JSON data with schemas that can now make use of "enumRef".

**Comment by marksparkza** [comment]
This is actually a really nice use case to use as a basis for demonstrating how to implement a custom keyword in jschon. I'll add explanatory notes to the jschon docs in due course, but in the meantime I've added an example, which should be straightforward to adapt to suit your requirements.

**Comment by ShahimEssaid** [comment]
@marksparkza, much appreciated! I'll look into this once it's clear that JSON Schema will be our validation language. I'm sure I'll have few more questions at that point.
