### ISSUE TITLE
"properties" in "allOf" and "additionalProperties"

### ISSUE THREAD

**Issue by ShahimEssaid** [marksparkza/jschon#16]
This is probably me not understanding how to use this combination of keywords properly.  I assumed the following schema would be valid against the JSON. This is a silly example to demonstrate the issue. My real use of this was to add a "additionalProperites": false  after this "allOf": https://github.com/cancerDHC/data-model-harmonization/blob/3e4639517586f8b260e8052417e6f32e66603c00/json-examples/home/shahim/schema-testing/schemas/testing-schema.json#L5816

Should the use of "properties" inside an "allOf" not annotate the property names used in the "allOF" so that the later "additionalProperties": false only fails for any other properties not handled in the "allOf"?

The demo schema:
```
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://ccdh/json/schema/testing",
  "allOf": [
    {
      "properties": {
        "foo": {}
      }
    },
    {
      "properties": {
        "bar": {}
      }
    }
  ],
  "additionalProperties": false
}

```

The JSON:
```
{
    "foo": "foo",
    "bar": "bar"
}
```

jschon.dev output:
```
The instance is invalid.
{
    "valid": false,
    "instanceLocation": "",
    "keywordLocation": "",
    "absoluteKeywordLocation": "http://ccdh/json/schema/testing#",
    "errors": [
        {
            "instanceLocation": "",
            "keywordLocation": "/additionalProperties",
            "absoluteKeywordLocation": "http://ccdh/json/schema/testing#/additionalProperties",
            "error": "The instance is disallowed by a boolean false schema"
        }
    ]
}
```

**Comment by marksparkza** [comment]
`unevaluatedProperties` should do the trick for you here.

`additionalProperties` only considers _adjacent_ `properties`, so in the above demo schema, `"additionalProperties": false` will always fail a non-empty JSON object.

`unevaluatedProperties` on the other hand considers all occurrences of `properties` in any adjacent subtree.
