### ISSUE TITLE
ImportError: cannot import name 'LocalSource' from 'jschon'

### ISSUE THREAD

**Issue by anantmittal** [marksparkza/jschon#21]
@marksparkza Thank you for this wonderful package. 

I am using `jschon-0.7.3`

I am trying to use this example as a template - https://github.com/marksparkza/jschon/blob/main/examples/load_from_files_2.py but I am seeing import errors. 

I can see the LocalSource class in https://github.com/marksparkza/jschon/blob/main/jschon/catalog/__init__.py but the class doesn't exist in locally installed package on my machine. 

I guess the pip package isn't updated to the latest code. Are there any plans to push the latest code to `PyPI`?

**Comment by marksparkza** [comment]
Hi @anantmittal,

Yes, a new release is in the works! Unfortunately I've had limited time available to work on jschon lately, so I can't say how soon that will be. In the meantime, there are a couple of options you can try:

- take a look at the 'stable' documentation examples which work for v0.7.3: https://jschon.readthedocs.io/en/stable/examples/file_based_schemas.html
- install the latest jschon code directly from GitHub with `pip install -e git+https://github.com/marksparkza/jschon.git#egg=jschon`

**Comment by anantmittal** [comment]
Thank you @marksparkza
