### ISSUE TITLE
Use Local Schemas only

### ISSUE THREAD

**Issue by stmty9** [marksparkza/jschon#22]
Not sure if this is an issue or what, but I am trying to load load a directory of schemas (these schemas don't have any `$id` tags and are referenced only via local file pointers in `$ref` tags - so I am not sure how to set the `URI` property accurately).

I feel like it should be able to auto load relative schemas via file paths (or at least attempt to given file permissions, etc, etc) and I shouldn't have to load each individually referenced schema by hand.

I saw in version 0.8.0, there is a `LocalSource`, but that still requires a URI, which are invalid based on my current file paths. 

Any tips appreciated ,thanks.

**Comment by marksparkza** [comment]
You should be able to do this by mapping an arbitrary base URI to your schema directory, and assigning a URI to your 'main' schema. Something like the following:

```py
from jschon import create_catalog, JSONSchema, URI

catalog = create_catalog('2020-12')
catalog.add_directory(URI('http://example.com/'), 'path/to/schemas')

main_schema = JSONSchema.loadf('path/to/schemas/main.json', uri=URI('http://example.com/main'))
```

So now any references are resolved with respect to your main schema's URI, which is based off a URI that is mapped to a directory.
