### ISSUE TITLE
Unknown keywords should produce annotations

### ISSUE THREAD

**Issue by marksparkza** [marksparkza/jschon#24]
As per the [spec](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.4.3.1).

**Comment by handrews** [comment]
This would be great to have.  I'm doing some work with a custom annotation vocabulary right now but the annotations are all trivial.  It's easy enough for me to set up but requires explaining to other folks.

This is also related to the ([recently clarified](https://github.com/json-schema-org/json-schema-spec/pull/1295)) intended purpose of setting vocabularies to `false` in `$vocabulary`.  Keywords from a `false` vocabulary are effectively the same as unrecognized non-vocabulary keywords.

I haven't had time so far to dig into jschon internals yet, but do let me know if I can help with anything in particular.

**Comment by marksparkza** [comment]
>  Keywords from a false vocabulary are effectively the same as unrecognized non-vocabulary keywords.

That makes sense.

> I haven't had time so far to dig into jschon internals yet, but do let me know if I can help with anything in particular.

Thanks! I have a lot on my plate at present and precious little spare capacity for jschon, so any help would be greatly appreciated. I've not settled on a particular approach, but I think an `UnknownKeyword` class could be a starting point. The `Metaschema` class should then support returning `UnknownKeyword` during schema construction, which would be associated with the unknown keyword in the schema and in turn selected during schema evaluation. The tricky bits are [here](https://github.com/marksparkza/jschon/blob/3ad9c961ad93db6fcbe3ffe3bb66c6751639aa94/jschon/jsonschema.py#L113) and [here](https://github.com/marksparkza/jschon/blob/3ad9c961ad93db6fcbe3ffe3bb66c6751639aa94/jschon/jsonschema.py#L117). In any case, you're welcome to dig in and create a PR if you have the time and find a way to get it working.
