### ISSUE TITLE
Cannot create catalog

### ISSUE THREAD

**Issue by mleehofman** [marksparkza/jschon#28]
Hi there,

After installing jschon, trying a few given examples and running the command `create_catalog('2020-12')` I get the following error

get_catalog
    raise CatalogError(f'Catalog name "{name}" not found.')
jschon.exceptions.CatalogError: Catalog name "catalog" not found.

Thank you in advance.

Regards,
Marcel Hofman

**Comment by marksparkza** [comment]
Hi, apologies for the slow response.

I can't reproduce this issue. Can you please provide a minimal working example that produces this exception?

**Comment by marksparkza** [comment]
Closing - cannot reproduce.
