### ISSUE TITLE
Add common prefix check to JSONPointer

### ISSUE THREAD

**Issue by SquareByte** [marksparkza/jschon#29]
It would be really nice to be able to check via a single method call if one pointer points to the container/parent of another. 

Perhaps even via operator overloading, though I'm not quite sure on the implications of that, or if I overlook some edgecases. For example:
```
ab = JSONPointer("/a/b")
abc = JSONPointer("/a/b/c")

assert ab < abc  # good?
assert ab in abc  # better?
assert abc - ab == JSONPointer("c")  # allow even this with relative pointers?
```

**Comment by marksparkza** [comment]
You can actually do this using slice notation, since `JSONPointer` implements the `Sequence` interface:
```
assert abc[:-1] == ab
```
