### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jugaadi** [marksparkza/jschon#33]
It would be really helpful if you can publish a roadmap to v1.0 along with the current production readiness of the package.

**Comment by marksparkza** [comment]
A roadmap to v1 is unfortunately not something I can commit to, and there are two main reasons for this. The first is that jschon development happens largely on an ad-hoc basis, and for the most part in my spare time. The second is that to some extent jschon is still in an experimental / exploratory phase of development, and I feel that it would be too limiting to constrain development by a roadmap at this stage.

Having said that, it's important to note a distinction between the development status of the package - currently "alpha" - and production readiness from an application perspective. While the alpha status allows for new features and API changes in the 0.x line of development, the core capabilities of the package - in particular, JSON Schema validation - will continue to work from one version to the next. Testing is key - every new jschon release must have a 100% test pass rate.

For users of the package, the same precautions apply regardless of the development status - pin your requirements to a specific version (e.g. 0.8.5) and make sure all your tests are passing when upgrading the package.

If it offers any reassurance as to production readiness, it may be of interest to know that I am in fact using jschon quite extensively in my "day job" - in systems due for production deployment later this year.

**Comment by jugaadi** [comment]
@marksparkza  Thanks for the update. Totally understand the reason for not publishing the roadmap. I was wondering if we can follow semantic versioning and adopt v1.0 if no breaking changes are expected anymore wrt the core capabilities ?

**Comment by marksparkza** [comment]
At this stage I think it would be premature to jump to v1.0. There _may_ still be breaking changes, even wrt core capabilities. For example, there are several breaking changes to core classes in the upcoming 0.9.0 release. This does not mean that a core feature will break or be removed, it just means that some users of the package might have to tweak their application code a bit if they're using part of the jschon API that has changed.

Closing - I hope the above provides some clarity on this.
