### ISSUE TITLE
Provide Error Code along with error messages in output format

### ISSUE THREAD

**Issue by jugaadi** [marksparkza/jschon#37]
As a library user, it would be helpful if jschon can provide numeric error codes( and name if possible) in addition to the error messages in output format since we may have to translate the same in other languages.

1. Current `error` node can point to error code instead of the message.
2. `title` and `description` annotations can be used to add more details of the error.

Prior art:
1. [HTTP Error Codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)
4. [Typescript Error Codes](https://typescript.tv/errors)
5. [Postgres Error Codes](https://www.postgresql.org/docs/current/errcodes-appendix.html)

**Comment by jugaadi** [comment]
Additional context: https://github.com/json-schema-org/json-schema-spec/issues/1282

**Comment by marksparkza** [comment]
I'm inclined to concur with Greg Dennis's view in the linked issue - that the keyword itself (which can be inferred from `keywordLocation`) can effectively be taken to be the error code.

I do agree though that error messaging in jschon needs work, in terms of allowing customization and localization. I'll create a separate issue for this.

**Comment by jugaadi** [comment]
PS: The suggestions by Greg Dennis will only be reflected in the next version of JSON Schema.
