### ISSUE TITLE
Loading a metaschema from disk doesn't load as a metaschema but instead as a JSONSchema

### ISSUE THREAD

**Issue by fxdgear** [marksparkza/jschon#39]
I've defined a collection of vocab and a metaschema on disk using json files. 

I'm trying to load these into the jschon  catalog, and then I also want to load the schema for my data source. 

When I load the schema, it raises the following error: 

```
jschon.exceptions.JSONSchemaError: The schema referenced by https://example.com/metaschema is not a metachema
```

**Comment by marksparkza** [comment]
The error is correct - a metaschema must be created explicitly.

**Comment by fxdgear** [comment]
@marksparkza Can you help me understand the reasoning why a metaschema must be created explicitly? 

Why can't I just load it from disk?

Is this the expected behavior for _all_ implementations of json-schema? 

thanks

**Comment by marksparkza** [comment]
Hi, @fxdgear 

The JSON Schema specification doesn't make any recommendations as to how input should be provided to an implementation.

It [says](https://json-schema.org/draft/2020-12/json-schema-core.html#name-detecting-a-meta-schema) that an implementation must know when to interpret a metaschema as a metaschema, and when to interpret it as a schema, when performing validation. It does not require that metaschemas are able to be loaded in the same way as schemas.

Generally speaking, metaschema authoring involves defining new vocabularies containing new keywords, and linking validation code with an implementation. In jschon, a few lines of boilerplate code are required to set up a metaschema object and link it with its keyword validators.
