### ISSUE TITLE
Object properties are only evaluated against core vocabulary when `$dynamicAnchor` is in place

### ISSUE THREAD

**Issue by ndellosa95** [marksparkza/jschon#43]
If you have a schema where you have the following

```json
{
  "$dynamicAnchor": "some_anchor",
  "type": "object",
  "properties": {
    "first": {
      "type": "not a valid type"
    }
  }
}
```

This schema will pass validation against its metaschema. Diving into the debugger, it seems that the individual properties (i.e. `first`) are only evaluated against the core vocabulary. Since `type` is not defined in the core vocabulary, the content of the `type` field is never evaluated. 

I have only tested this with `$dynamicAnchor` so not sure if regular `$anchor` also produces the same result. I have also only tested this with `2020-12`. I can add more details later if necessary.

**Comment by marksparkza** [comment]
I'm unable to reproduce this.

Running the following code:
```py
from jschon import JSONSchema, create_catalog

create_catalog('2020-12')
schema = JSONSchema({
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$dynamicAnchor": "some_anchor",
    "type": "object",
    "properties": {
        "first": {
            "type": "not a valid type"
        }
    }
})
result = schema.validate()
```
`result.valid` gives `False`, and `result.output('basic')` gives the errors produced by the meta-schema.
