### ISSUE TITLE
Support for Python 3.11?

### ISSUE THREAD

**Issue by handrews** [marksparkza/jschon#46]
I've run the tests with Python 3.11.2:

* the main tests all pass
* `--testsuite-optionals` has the same pass/fail numbers as with 3.10
* `--testsuite-formats` has the same pass/fail numbers as with 3.10

I did not looking into the optionals/formats errors in detail, but it seems like the behavior is the same on 3.10 and 3.11.

Would there be anything more to supporting 3.11 than updating the version list in `setup.py` an adding `py311` to `tox.ini`?  Is that worth doing?

**Comment by marksparkza** [comment]
Thanks for verifying the tests with 3.11 - please go ahead with a PR, including change log under miscellaneous. Please also mention 3.11 in TESTING.rst.
