### ISSUE TITLE
Validating Yaml (with JSON schema) like Visual Studio Code

### ISSUE THREAD

**Issue by ws1088** [marksparkza/jschon#5]
Hi @marksparkza,
I am trying to generate a list of errors on a yaml file (with a JSON schema) to check for issues before yaml writers check in their file. They are already using the JSON schema on vscode, but of course they can ignore the errors :)
Can I use `jschon` to read in a yaml file and generate a list of issues like those from vscode?
Thanks in advance!

**Comment by marksparkza** [comment]
Hi! Jschon does not read yaml files. However, you could use something like [pyyaml](https://github.com/yaml/pyyaml/) to read in your yaml doc, and the resulting object can be passed directly to the `JSON` constructor. You can then use jschon to validate that `JSON` instance and produce errors upon failure. I am currently working on formatting and usability of output/errors - though primarily intended to provide the various [output formats](https://json-schema.org/draft/2020-12/json-schema-core.html#output) defined in the JSON Schema spec. You will probably have to do some post-processing of the error output to get it into a list of issues the way you want it.

**Comment by ws1088** [comment]
thanks, hopefully the usability of the output/errors would be similar to those in vscode :)
