### ISSUE TITLE
Catalogue error when loading schema

### ISSUE THREAD

**Issue by michaelmior** [marksparkza/jschon#6]
Whenever I try to load a schema, I get the error below.

`jschon.exceptions.CatalogueError: File not found for 'https://json-schema.org/draft/2019-09/schema'`

I have tried creating a default catalogue with `Catalogue.create_default_catalogue('2019-09')` but then I get the following:

`AttributeError: type object 'Catalogue' has no attribute 'create_default_catalogue'`

Not sure if this is a bug or if I'm doing something wrong.

**Comment by michaelmior** [comment]
I see on taking a closer look that the latest PyPI release doesn't seem to contain `create_default_catalog`. Using the latest from the main branch works for me. Would it be possible to have another release?

**Comment by marksparkza** [comment]
Hi @michaelmior,

Thanks for your interest in jschon. Yes - I am planning to do another release within the next few days.

**Comment by michaelmior** [comment]
Great! Thank you :)

**Comment by MinionAttack** [comment]
> Great! Thank you :)

How do you install it from the master branch? I'm trying to install it manually in a virtual environment but I get an error.

**Comment by michaelmior** [comment]
@MinionAttack 

`pip install -e git+https://github.com/marksparkza/jschon.git#egg=jschon`

**Comment by marksparkza** [comment]
A new version is available!

**Comment by michaelmior** [comment]
@marksparkza Thank you!
