### ISSUE TITLE
Unable to install jschon via pip

### ISSUE THREAD

**Issue by MinionAttack** [marksparkza/jschon#7]
Hi,

If I try to install jschon I get this error:

```
$ pip3 install jschon
ERROR: Could not find a version that satisfies the requirement jschon (from versions: none)
ERROR: No matching distribution found for jschon
```

And if I specify a version too:

```
$ pip3 install jschon==0.2.0
ERROR: Could not find a version that satisfies the requirement jschon==0.2.0 (from versions: none)
ERROR: No matching distribution found for jschon==0.2.0
```

I have tried both pip and pip3 but I get the same result.

**Comment by michaelmior** [comment]
What version of Python are you using? Only Python 3.8 and 3.9 are supported.

**Comment by MinionAttack** [comment]
> What version of Python are you using? Only Python 3.8 and 3.9 are supported.

Oh, I'm using 3.6.9. I guess I need to update my distribution then.
